import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertInCity1747695602834 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        INSERT INTO vendas.city(id, name, state_id) VALUES 
        (1, 'Afonso Cláudio', 8),
        (2, 'Água Doce do Norte', 8),
        (3, 'Águia Branca', 8),
        (4, 'Alegre', 8),
        (5, 'Alfredo Chaves', 8),
        (6, 'Alto Rio Novo', 8),
        (7, 'Anchieta', 8),
        (8, 'Apiacá', 8),
        (9, 'Aracruz', 8),
        (10, 'Atilio Vivacqua', 8),
        (11, 'Baixo Guandu', 8),
        (12, 'Barra de São Francisco', 8),
        (13, 'Boa Esperança', 8),
        (14, 'Bom Jesus do Norte', 8),
        (15, 'Brejetuba', 8),
        (16, 'Cachoeiro de Itapemirim', 8),
        (17, 'Cariacica', 8),
        (18, 'Castelo', 8),
        (19, 'Colatina', 8),
        (20, 'Conceição da Barra', 8),
        (21, 'Conceição do Castelo', 8),
        (22, 'Divino de São Lourenço', 8),
        (23, 'Domingos Martins', 8),
        (24, 'Dores do Rio Preto', 8),
        (25, 'Ecoporanga', 8),
        (26, 'Fundão', 8),
        (27, 'Governador Lindenberg', 8),
        (28, 'Guaçuí', 8),
        (29, 'Guarapari', 8),
        (30, 'Ibatiba', 8),
        (31, 'Ibiraçu', 8),
        (32, 'Ibitirama', 8),
        (33, 'Iconha', 8),
        (34, 'Irupi', 8),
        (35, 'Itaguaçu', 8),
        (36, 'Itapemirim', 8),
        (37, 'Itarana', 8),
        (38, 'Iúna', 8),
        (39, 'Jaguaré', 8),
        (40, 'Jerônimo Monteiro', 8),
        (41, 'João Neiva', 8),
        (42, 'Laranja da Terra', 8),
        (43, 'Linhares', 8),
        (44, 'Mantenópolis', 8),
        (45, 'Marataízes', 8),
        (46, 'Marechal Floriano', 8),
        (47, 'Marilândia', 8),
        (48, 'Mimoso do Sul', 8),
        (49, 'Montanha', 8),
        (50, 'Mucurici', 8),
        (51, 'Muniz Freire', 8),
        (52, 'Muqui', 8),
        (53, 'Nova Venécia', 8),
        (54, 'Pancas', 8),
        (55, 'Pedro Canário', 8),
        (56, 'Pinheiros', 8),
        (57, 'Piúma', 8),
        (58, 'Ponto Belo', 8),
        (59, 'Presidente Kennedy', 8),
        (60, 'Rio Bananal', 8),
        (61, 'Rio Novo do Sul', 8),
        (62, 'Santa Leopoldina', 8),
        (63, 'Santa Maria de Jetibá', 8),
        (64, 'Santa Teresa', 8),
        (65, 'São Domingos do Norte', 8),
        (66, 'São Gabriel da Palha', 8),
        (67, 'São José do Calçado', 8),
        (68, 'São Mateus', 8),
        (69, 'São Roque do Canaã', 8),
        (70, 'Serra', 8),
        (71, 'Sooretama', 8),
        (72, 'Vargem Alta', 8),
        (73, 'Venda Nova do Imigrante', 8),
        (74, 'Viana', 8),
        (75, 'Vila Pavão', 8),
        (76, 'Vila Valério', 8),
        (77, 'Vila Velha', 8),
        (78, 'Vitória', 8),
        (79, 'Acrelândia', 1),
        (80, 'Assis Brasil', 1),
        (81, 'Brasiléia', 1),
        (82, 'Bujari', 1),
        (83, 'Capixaba', 1),
        (84, 'Cruzeiro do Sul', 1),
        (85, 'Epitaciolândia', 1),
        (86, 'Feijó', 1),
        (87, 'Jordão', 1),
        (88, 'Mâncio Lima', 1),
        (89, 'Manoel Urbano', 1),
        (90, 'Marechal Thaumaturgo', 1),
        (91, 'Plácido de Castro', 1),
        (92, 'Porto Acre', 1),
        (93, 'Porto Walter', 1),
        (94, 'Água Branca', 2),
        (95, 'Anadia', 2),
        (96, 'Arapiraca', 2),
        (97, 'Atalaia', 2),
        (98, 'Barra de Santo Antônio', 2),
        (99, 'Barra de São Miguel', 2),
        (100, 'Batalha', 2),
        (101, 'Belém', 2),
        (102, 'Belo Monte', 2),
        (103, 'Boca da Mata', 2),
        (104, 'Branquinha', 2),
        (105, 'Cacimbinhas', 2),
        (106, 'Cajueiro', 2),
        (107, 'Campestre', 2),
        (108, 'Campo Alegre', 2),
        (109, 'Amapá', 3),
        (110, 'Calçoene', 3),
        (111, 'Cutias', 3),
        (112, 'Ferreira Gomes', 3),
        (113, 'Itaubal', 3),
        (114, 'Laranjal do Jari', 3),
        (115, 'Macapá', 3),
        (116, 'Mazagão', 3),
        (117, 'Oiapoque', 3),
        (118, 'Pedra Branca do Amapari', 3),
        (119, 'Porto Grande', 3),
        (120, 'Pracuúba', 3),
        (121, 'Santana', 3),
        (122, 'Serra do Navio', 3),
        (123, 'Tartarugalzinho', 3),
        (124, 'Alvarães', 4),
        (125, 'Amaturá', 4),
        (126, 'Anamã', 4),
        (127, 'Anori', 4),
        (128, 'Apuí', 4),
        (129, 'Atalaia do Norte', 4),
        (130, 'Autazes', 4),
        (131, 'Barcelos', 4),
        (132, 'Barreirinha', 4),
        (133, 'Benjamin Constant', 4),
        (134, 'Beruri', 4),
        (135, 'Boa Vista do Ramos', 4),
        (136, 'Boca do Acre', 4),
        (137, 'Borba', 4),
        (138, 'Caapiranga', 4),
        (139, 'Salvador', 5),
        (140, 'Feira de Santana', 5),
        (141, 'Vitória da Conquista', 5),
        (142, 'Camaçari', 5),
        (143, 'Itabuna', 5),
        (144, 'Juazeiro', 5),
        (145, 'Lauro de Freitas', 5),
        (146, 'Ilhéus', 5),
        (147, 'Jequié', 5),
        (148, 'Teixeira de Freitas', 5),
        (149, 'Barreiras', 5),
        (150, 'Alagoinhas', 5),
        (151, 'Porto Seguro', 5),
        (152, 'Simões Filho', 5),
        (153, 'Paulo Afonso', 5),
        (154, 'Açailândia', 10),
        (155, 'Afonso Cunha', 10),
        (156, 'Água Doce do Maranhão', 10),
        (157, 'Alcântara', 10),
        (158, 'Aldeias Altas', 10),
        (159, 'Altamira do Maranhão', 10),
        (160, 'Alto Alegre do Maranhão', 10),
        (161, 'Alto Alegre do Pindaré', 10),
        (162, 'Alto Parnaíba', 10),
        (163, 'Amapá do Maranhão', 10),
        (164, 'Amarante do Maranhão', 10),
        (165, 'Anajatuba', 10),
        (166, 'Anapurus', 10),
        (167, 'Apicum-Açu', 10),
        (168, 'Araguanã', 10);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        DELETE FROM vendas.city;
    `);
  }
}
